#!/bin/sh
#$Id: testsuite,v 1.1.1.1 2003/05/07 02:13:12 lfan Exp $

rm -f testgdbm.dat

./testgdbm testgdbm.dat foo bar
./testgdbm testgdbm.dat foo baz
./testgdbm testgdbm.dat bar foo
./testgdbm testgdbm.dat foo
./testgdbm testgdbm.dat bar
./testgdbm testgdbm.dat
./testgdbm testgdbm.dat -foo
./testgdbm testgdbm.dat
